version: '3'

services:
  client:
    build: ./frontend
    ports:
      - 3000:3000
    volumes: 
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      

  server:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/backend-app
      - node_modules_b:/usr/src/backend-app/node_modules
    depends_on: 
      - mongo

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes: 
  node_modules:
  node_modules_b:
  data: